name: 'dart_playground'
version: 0.0.1
description: A web server built using the shelf package.
#author: Your Name <email@example.com>
#homepage: https://www.example.com

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  args: ^0.13.0
  dice: ^1.6.5
  shelf: ^0.6.0
  shelf_rpc: ^0.0.3

dev_dependencies:
  mockito: ^0.11.0
  test: ^0.12.0